export const ErrorCodes = {
  CONFIG_MISSING_API_KEY: "CONFIG_MISSING_API_KEY",
  CONFIG_INVALID_BASE_URL: "CONFIG_INVALID_BASE_URL",
  CONFIG_MODEL_MISSING: "CONFIG_MODEL_MISSING",
  IMAGE_FILE_NOT_FOUND: "IMAGE_FILE_NOT_FOUND",
  IMAGE_PERMISSION_DENIED: "IMAGE_PERMISSION_DENIED",
  IMAGE_UNSUPPORTED_FORMAT: "IMAGE_UNSUPPORTED_FORMAT",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",
  IMAGE_DECODE_FAILED: "IMAGE_DECODE_FAILED",
  PROVIDER_UNAUTHORIZED: "PROVIDER_UNAUTHORIZED",
  PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  PROVIDER_BAD_REQUEST: "PROVIDER_BAD_REQUEST",
  PROVIDER_UNSUPPORTED_IMAGE: "PROVIDER_UNSUPPORTED_IMAGE",
  PROVIDER_INVALID_RESPONSE: "PROVIDER_INVALID_RESPONSE",
  DB_OPEN_FAILED: "DB_OPEN_FAILED",
  DB_MIGRATION_FAILED: "DB_MIGRATION_FAILED",
  CACHE_READ_FAILED: "CACHE_READ_FAILED",
  CACHE_WRITE_FAILED: "CACHE_WRITE_FAILED",
  BATCH_NO_MATCH: "BATCH_NO_MATCH",
  BATCH_PARTIAL_FAILED: "BATCH_PARTIAL_FAILED",
  RUNTIME_ERROR: "RUNTIME_ERROR",
  ARGUMENT_ERROR: "ARGUMENT_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

